spring.application.name=wynajem-aut
spring.datasource.url=jdbc:mysql://localhost:55555/samochody  # PORT 55555
spring.datasource.username=root
spring.datasource.password=
spring.mvc.view.suffix=.html

# KONFIGURACJA FAKE SMTP
# dziala na localhost:2525
spring.mail.host=localhost
spring.mail.port=2525

spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# nadawca maili
app.email.from=biuro@wynajem-aut.pl

# jesli fakeSMTP nie dziala, nie crashuj apki
spring.mail.test-connection=false